project:
  type: "website"
  title: "CP322 Machine Learning (Winter 2026)"
  output-dir: _output
  resources:
    - login
  render:
    - "index.qmd"
    - "2026/*.qmd"
    - "2026/weeks/week01/*.qmd"
    - "2026/weeks/week02/*.qmd"
    - "2026/weeks/week03/*.qmd"

website:
  title: "CP322 Machine Learning (Winter 2026)"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card: 
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: 2026/index.qmd
        text: "ğŸ  Home"
      - href: 2026/syllabus.qmd
        text: "ğŸ““ Syllabus"
      - href: 2026/tools.qmd
        text: "ğŸ““ Software Tools"
      - href: 2026/email.qmd
        text: "ğŸ““ Emailing Rules"
      # - href: 2023/communication.qmd
      #   text: "ğŸ“Ÿ Communication"
      # - href: 2023/assignments.qmd
      #   text: "âœï¸ Assignments"
      #   contents:
      #     - href: 2023/assignments/assignment01.qmd
      #       text: "ğŸ“ Assignment 01"
      #     - href: 2023/assignments/assignment02.qmd
      #       text: "ğŸ“ Assignment 02"
      #     - href: 2023/assignments/group_project.qmd
      #       text: "ğŸ‘¥ Group Project"
      - section: "ğŸ—“ï¸ Weeks"
        contents:
         - href: 2026/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2026/weeks/week01/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2026/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material

         - href: 2026/weeks/week03/page.qmd
           text: Week 03
           contents:
             - href: 2026/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, S.S.Sehra" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [Sukhjit Singh Sehra](https://ssehra.com/)
    author-meta: Dr. Sukhjit Singh Sehra
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true
    include-before-body:
      - helpers/access-guard.html

#margin-header: |
# ![](/figures/logos/MY_INSTITUTION.png)

